#数据库连接
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/person?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    typeAliasesPackage: com.example.entity
    mapperLocations: classpath:mappers/*.xml

  mvc:
    view:
      prefix: /templates
      suffix: .html

  thymeleaf:
    cache: false

  web:
    resources:
      static-locations: file:D/image , classpath:static
#服务器端口
server:
  port: 8080
  